storage:
  #  What type of storage to use.
  #    Options:
  #      0: File storage (default)
  #      1: MySQL storage
  #      2: RAM storage (dev use only)
  type: 0
  mysql:
    host: localhost
    dbname: exilepearl
    port: 3306
    username: bukkit
    password: ''
    connection_timeout: 5000
    idle_timeout: 5000
    max_lifetime: 5000
    pool_size: 5
    # When true, the MySQL storage will attempt to migrate
    # PrisonPearl data when it connects for the first time.
    migrate_pp: false
    migrate_dbname: prisonpearl


general:
  # The timeout for the /suicide command before the player actually dies.
  suicide_time_sec: 180


pearls:
  # When true, pearls that are outside the world border will be freed during
  # a decay operation.
  autofree_worldborder: true
  free_by_throwing: false
  # When true, players will only be pearled if the killer has a pearl in
  # their hotbar.
  hotbar_needed: true
  # How often the decay task runs.
  decay_interval_min: 60
  # The raw health amount that is removed with each decay operation.
  decay_amount: 1
  decay_timeout_min: 10080
  # The starting health value of pearls when they are created.
  start_value: 12
  # The maximum health value.
  # This will determine the displayed health percent value.
  max_value: 336
  # The materials used to repair pearls.
  # The repair value is how many health points are repaired for each item.
  repair_materials:
    PRISON:
      emerald:
        material: EMERALD
        repair: 3
    EXILE:
      obsidian:
        material: OBSIDIAN
        repair: 3
  # The amount of damage to deal to players when they are inside a
  # bastion field they don't have perms on.
  bastion_harm_amount: 2.0
  # The materials used to upgrade pearls from exile to prison.
  # The repair value is how many are required.
  upgrade_materials:
    special_diamond_thing:
      material: DIAMOND
      repair: 1
      lore:
        - This is used to upgrade exile pearls to prison pearls
  # Whether or not prison pearls can be stolen by killing a summoned player.
  allow_pearl_stealing: true


help_item:
  # When true, a help item is generated for pearled players on respawn.
  enabled: true
  item_name: "You've been exiled!"
  item_text:
    - "<a>You are exiled."
    - ""
    - "<n>Another player has imprisoned you in an exile pearl."
    - "<n>Your in-game actions will be limited until you are freed."
    - "<n>You can type <c>/ep locate to see the location of your pearl."


damage_log:
  # When true, the damage log task is enabled to track who is awarded pearls.
  # If this is disabled, a pearl will only be awarded by a direct kill.
  enabled: true
  # The algorithm type to use when awarding pearls.
  # Options:
  #   0: Most Recent - Use most recent damager to award the pearl.
  #   1: Most Damage - Use highest tracked damager to award the pearl.
  algorithm: 0
  # The interval in ticks for how often the damage tracking task runs.
  tick_interval: 20
  # The damage amount to remove at each run interval.
  # Example:
  #   If tick_interval=20 and decay_amount=1,
  #   a player dealing 10 damage will be tracked for 10 seconds (20t/second).
  decay_amount: 1.0
  # The maximum damage amount to track for a given damager.
  max_amount: 30.0
  # The base damage to apply for splash potions. This only applies to harming,
  # poison, and weakness splash potions.
  # An extended or upgraded potion has a 2x multiplier of this value.
  # The potion intensity (0 - 1.0) is also used as a multiplier,
  # so a player may not always be dealt the full potion damage amount.
  potion_damage: 6.0


rules:
  # The radius around their pearl that an exiled player can't enter.
  # Set this value to 0 to disable the radius.
  pearl_radius: 1000
  # Worlds that pearls are not allowed to be stored in.
  disallowed_worlds:

  # When true, exiled players can use the /suicide command.
  suicide: true
  # When false, exiled players can't break any blocks.
  mine_blocks: true
  # When false, exiled players can't harm other players.
  pvp: false
  # When false, exiled players can't empty buckets or move them to
  # other inventories.
  use_buckets: false
  # When false, exiled players can't fill buckets (unless milk_cows is true).
  fill_buckets: false
  place_tnt: false
  # When false, exiled players can't set things on fire.
  ignite: false
  use_beds: false
  use_potions: false
  throw_pearls: false
  # When false, exiled players can't harm protected mobs.
  kill_protected_mobs: false
  # Mobs that are protected when kill_mobs is set to false.
  protected_mobs:
    - Sheep
    - Cow
    - Pig
    - Horse
  # When false, exiled players can't harm pet mobs.
  kill_pets: false
  # When false, exiled players can't collect xp orbs.
  collect_xp: true
  enchant: true
  use_anvils: true
  milk_cows: true
  fill_cauldrons: true

  # [Brewery plugin]
  brew: true
  # When false, exiled players can't drink Brewery brews.
  drink_brews: true

  # [CivChat2 plugin]
  # When false, exiled players can't chat locally.
  chat_local: false

  # [Bastion plugin]
  create_bastion: false
  damage_bastion: false
  # When false, exiled players can't enter bastion fields that
  # they aren't a member of.
  enter_bastion: false

  # [Citadel plugin]
  damage_reinforcement: false

  # [JukeAlert plugin]
  place_snitch: false
